options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/protean-cistern-460803-q3/cloud-run-source-deploy/zenith-assistant:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/protean-cistern-460803-q3/cloud-run-source-deploy/zenith-assistant:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - your-cloud-run-service
      - --image
      - asia-northeast1-docker.pkg.dev/protean-cistern-460803-q3/cloud-run-source-deploy/zenith-assistant:latest
      - --region
      - asia-northeast1
      - --platform
      - managed
      - --allow-unauthenticated
